import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Toaster } from "@/components/ui/sonner"
import TrpcProvider from "./_trpc/TrpcProvider";
import NextAuthSessionProvider from "@/components/auth/NextAuthSessionProvider";

export const metadata: Metadata = {
  title: "GrowPoint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TrpcProvider>
        <NextAuthSessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <body>
              {children}
              <Toaster />
            </body>
          </ThemeProvider>
        </NextAuthSessionProvider>
      </TrpcProvider>
    </html>
  );
}
